services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.DEV
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app/app  # For hot reload
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    env_file:
      - .env.DEV
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 